### ISSUE TITLE
Make London happen!

### ISSUE THREAD

**Issue by muan** [jlord/hack-spots#14]
Just added The Breakfast Club, but noticed there isn't a postcode field. Postcode is pretty useful in London, it is sometimes more accurate than searching by street number/name! So it'd be rad if we can have a postcode field, it doesn't need to do anything even.

**Comment by jlord** [comment]
Yes! I agree and had forgotten about cities where postcodes are really useful. 
- I added a column to the spreadsheet for it (people can leave it blank still, too)
- When you click on a place in the table and it shows it's card of info at the top, it will now display the postcode if there is one.

:uk:
