### ISSUE TITLE
Something broke? 

### ISSUE THREAD

**Issue by alysonla** [jlord/hack-spots#15]
I think something broke cause the webpage is not pulling through the google doc info? 

![screen shot 2013-12-08 at 7 09 02 pm](https://f.cloud.github.com/assets/2623954/1702081/69f7df9a-607f-11e3-959c-d7c570970c28.png)

**Comment by jlord** [comment]
It works for me so I think that you're experiencing _this one weird bug_ where Google doesn't like it when you are not signed in or signed in too many accounts or something... but it then blocks getting the data. I haven't figured it out, but when it happens to me I usually open a new tab and log into gmail and then refresh Hack Spots. It's very weird! Let me know if that doesn't work!

**Comment by alysonla** [comment]
Ahhh that worked so weird! Thanks @jlord !!
