### ISSUE TITLE
New google spreadsheets

### ISSUE THREAD

**Issue by aryehbeitz** [jlord/hack-spots#16]
When I enter in the spreadsheet key, on a spreadsheet created using the new google spreadsheet, it doesn't work.
I don't know how to make a 'old' google spreadsheet.

**Comment by jlord** [comment]
If you are in fact using the new google spreadsheet it will not work.
Google has changed spreadsheets but has not updated their documentation to
show how to work with the new spreadsheets so I can't build anything to
support them. They will, I'm told, be rolling out stuff soon and I plan on
updating everything to work with new spreadsheets as soon as I have the
information.

Jessica

**Comment by alicetragedy** [comment]
+1. 
Wanted to make a spreadsheet only for my city, got a "No 'Access-Control-Allow-Origin' header is present on the requested resource." error. Sadface. :crying_cat_face:

**Comment by alicetragedy** [comment]
Anyway, since I am stubborn @aryehbeitz I looked it up, and right now the workaround is to create your spreadsheet as an "old" version using this link: https://g.co/oldsheets 
(source: https://support.google.com/drive/answer/3541068?p=help_new_sheets&rd=1)
I'm going to try it out now and see if it works. Jippiii!

**Comment by jlord** [comment]
YAY! YAY! Tabletop works with new Sheets now! https://github.com/jsoma/tabletop/pull/48

I'm about the update the tabletop here. 

:balloon: :balloon:

**Comment by yvahava** [comment]
According to their documentation you will simply need to publish the document on the web and it will work.  I had a similar issue and that fixed the problem.
