### ISSUE TITLE
How do I move the NumberofSpots line to another part of the page?

### ISSUE THREAD

**Issue by mattsafaii** [jlord/hack-spots#19]
I'm trying to move the "_x_ hack spots strong" line to the footer of the page but it isn't working. It is correctly displaying the number of items in my spreadsheet, but when I try to move it to anywhere else on the page using this `<div id="theNumberofSpots"></div>` or `<p><strong><span class="red-text">{{numberOfSpots}}</span> hack spots strong!</p>`, it doesn't work. 

Any help would be appreciated!
![screen shot 2014-10-23 at 3 11 08 pm](https://cloud.githubusercontent.com/assets/3858718/4762403/97e23d24-5b01-11e4-8f57-830501b9e817.png)

**Comment by jlord** [comment]
Hi! Sorry so late in replying to this—I cloned your fork on my machine and tested it and got it to work. You should be able to move `<div id="theNumberofSpots"></div>` anywhere within the html and it will work. 

I moved it to:

``` html
<div id="footer">
        <div id="contact">
            <div id="theNumberofSpots"></div>
            <!--<a href="http://www.github.com/mcmxc/hoops" target="_blank">Github</a>-->
            <a href="http://www.twitter.com/matt_nazarian" target="_blank">Twitter</a>
            <a href="mailto:matt@mcmxc.co">Email</a>
        </div>
    </div><!--end footer -->
```

![screen shot 2014-11-17 at 11 46 44 am](https://cloud.githubusercontent.com/assets/1305617/5069219/6fe04d3c-6e4f-11e4-947f-b2e50b18e4f6.png)

Does that help?

**Comment by jlord** [comment]
PS—the page looks awesome! :basketball:
