### ISSUE TITLE
mapbox account. 

### ISSUE THREAD

**Issue by dougaitken** [jlord/hack-spots#32]
I haven't seen it mentioned anywhere, but should I create my own Mapbox project if I'm using hack-spots as a base for a different project?

**Comment by jlord** [comment]
I believe the tiles I have should still work if you want to use them, but if you wanted to design your own tiles then yes you would need to create a project on Mapbox.

**Comment by dougaitken** [comment]
Sweet, I just wasn't wanting to use up someone's quota :+1:
